version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - laravel

    db:
        image: mysql:8.0
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=banking
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=adminadmin
            - MYSQL_ROOT_PASSWORD=rootpassword

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
